version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Concatenate all pom.xml
          command: cat pom.xml */pom.xml > allpoms.xml
      - restore_cache:
          key: cache-{{ checksum "allpoms.xml" }}
      - run:
          name: Install dependencies
          # https://issues.apache.org/jira/browse/MDEP-568 for --fail-never
          command: ./mvnw --settings settings.xml --batch-mode --fail-never dependency:go-offline -DexcludeGroupIds=com.apollographql.federation
      - save_cache:
          paths:
            - ~/.m2
          key: cache-{{ checksum "allpoms.xml" }}
      - run:
          name: Build, install, test
          command: ./mvnw --settings settings.xml --batch-mode install test -Dgpg.skip
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

workflows:
  version: 2
  Build and Test:
    jobs:
      - build
